### ISSUE TITLE
IRMC

### ISSUE THREAD

**Issue by LindenCX** [mmurayama/fujitsu-redfish-samples#1]
Is there a way to get the AVR java applet with curl? Supermicro and others have this ability by storing the authentication cookies and requesting the .jnlp file directly.

```
COOKIE=`curl -k --data "WEBVAR_USERNAME=$IPMI_USER&WEBVAR_PASSWORD=$IPMI_PASS" https://$HOST/rpc/WEBSES/create.asp 2> /dev/null | grep SESSION_COOKIE | cut -d\' -f 4`
curl -k -v --cookie SessionCookie=$COOKIE "https://$HOST/Java/jviewer.jnlp?EXTRNIP=$HOST&JNLPSTR=JViewer" -o jviewer.jnlp
```

I can login using the digest auth method with curl to iRMC 4, but haven't found a method to get the java applet.

Thanks!

**Comment by mmurayama** [comment]
For iRMC S4, you can download the AVR jnlp file using curl like this.

`$ curl -k -s -u <irmc user>:<irmc pasword> https://<irmc ip address>/avr.jnlp -o avr.jnlp`



example)
`$ curl -k -s -u admin:admin https://192.168.10.10/avr.jnlp -o avr.jnlp`

**Comment by LindenCX** [comment]
@mmurayama Thank you, this is very appreciated. 

I had to add the _--digest_ flag to curl for iRMC S4, as such:

`curl -k -s --digest -u admin:admin https://127.0.0.1/avr.jnlp -o avr.jnlp`
